CREATE DATABASE mydb;



USE mydb;
CREATE TABLE dept (
  id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT COMMENT 'ID, 主键',
  name VARCHAR(20) NOT NULL UNIQUE COMMENT '部门名称',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间'
) COMMENT '部门表';


CREATE TABLE emp(
    id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT COMMENT 'ID,主键',
    username VARCHAR(20) NOT NULL UNIQUE COMMENT '用户名',
    password VARCHAR(50) DEFAULT '123456' COMMENT '密码',
    name VARCHAR(10) NOT NULL COMMENT '姓名',
    gender TINYINT UNSIGNED NOT NULL COMMENT '性别, 1:男, 2:女',
    phone CHAR(11) NOT NULL UNIQUE COMMENT '手机号',
    job TINYINT UNSIGNED COMMENT '职位, 1:班主任, 2:讲师, 3:学工主管, 4:教研主管, 5:咨询师',
    salary INT UNSIGNED COMMENT '薪资',
    image VARCHAR(300) COMMENT '头像',
    entry_date DATE COMMENT '入职日期',
    dept_id INT UNSIGNED COMMENT '部门ID',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间'
) COMMENT '员工表';


CREATE TABLE emp_log(
    id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT COMMENT 'ID, 主键',
    operate_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '操作时间',
    info VARCHAR(2000) COMMENT '日志信息'
) COMMENT '员工日志表';

CREATE TABLE clazz(
    id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT COMMENT 'ID,主键',
    name VARCHAR(30) NOT NULL UNIQUE COMMENT '班级名称',
    room VARCHAR(20) COMMENT '班级教室',
    begin_date DATE NOT NULL COMMENT '开课时间',
    end_date DATE NOT NULL COMMENT '结课时间',
    master_id INT UNSIGNED COMMENT '班主任ID, 关联员工表ID',
    subject TINYINT UNSIGNED NOT NULL COMMENT '学科, 1:Java, 2:前端, 3:大数据, 4:Python, 5:Go, 6:嵌入式',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间'
) COMMENT '班级表';


CREATE TABLE student(
  id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT COMMENT 'ID,主键',
  name VARCHAR(10) NOT NULL COMMENT '姓名',
  no CHAR(10) NOT NULL UNIQUE COMMENT '学号',
  gender TINYINT UNSIGNED NOT NULL COMMENT '性别, 1:男, 2:女',
  phone VARCHAR(11) NOT NULL UNIQUE COMMENT '手机号',
  id_card CHAR(18) NOT NULL UNIQUE COMMENT '身份证号',
  is_college TINYINT UNSIGNED NOT NULL COMMENT '是否来自院校, 1:是, 0:否',
  address VARCHAR(100) COMMENT '联系地址',
  degree TINYINT UNSIGNED COMMENT '最高学历, 1:初中, 2:高中, 3:大专, 4:本科, 5:硕士, 6:博士',
  graduation_date DATE COMMENT '毕业时间',
  clazz_id INT UNSIGNED NOT NULL COMMENT '班级ID, 关联班级表ID',
  violation_count TINYINT UNSIGNED DEFAULT 0 NOT NULL COMMENT '违纪次数',
  violation_score TINYINT UNSIGNED DEFAULT 0 NOT NULL COMMENT '违纪扣分',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间'
) COMMENT '学员表';

