spring:
  application:
    name: demo

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      max-file-size: ${MULTIPART_MAX_FILE_SIZE:10MB}
      max-request-size: ${MULTIPART_MAX_REQUEST_SIZE:100MB}

mybatis:
  mapper-locations: classpath:com/wyt/mapper/*.xml
  type-aliases-package: com.wyt.pojo
  configuration:
    map-underscore-to-camel-case: true

pagehelper:
  reasonable: true
  helper-dialect: mysql

logging:
  level:
    org.springframework.jdbc.datasource.DataSourceTransactionManager: INFO
    org.springframework.jdbc.support.JdbcTransactionManager: INFO
    org.springframework.transaction.interceptor: INFO

aliyun:
  oss:
    endpoint: ${ALIYUN_OSS_ENDPOINT}
    bucket-name: ${ALIYUN_OSS_BUCKET_NAME}
    region: ${ALIYUN_OSS_REGION}

debug: false
